services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./frontend:/app/frontend
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    container_name: smollm2_model
    ports:
      - "8001:8001"
    volumes:
      - hf_cache:/app/.cache/huggingface
    restart: unless-stopped

volumes:
  hf_cache:
